# .github/workflows/pypi-publish.yml
name: Publish Python Package to PyPI with UV

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI with UV
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/knmi-py

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build package with UV
        run: uv build --sdist --wheel --no-sources

      - name: Publish package to PyPI with UV
        run: uv publish